# Generated by Django 5.1.3 on 2024-11-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='location',
        ),
    ]
