# Generated by Django 5.1.3 on 2024-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_rename_body_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='money',
            field=models.DecimalField(decimal_places=2, help_text='NTD dollar', max_digits=7),
        ),
    ]
